import {
  Calendar,
  Webhook,
  Play,
  Bot,
  Workflow,
  HelpCircle,
  RefreshCw,
  Clock,
  Globe,
  Terminal,
  Code2,
  Layers,
  Users,
  FileText,
  GitBranch,
  ShieldCheck,
  CheckCircle,
} from "lucide-react";
import type { TipoNodeItem } from "./types.js";

export const TIPOS_NODE_CATALOGO: TipoNodeItem[] = [
  // Gatilhos
  {
    tipo: "cron",
    rotulo: "Gatilho Cron / Agenda",
    categoria: "gatilhos",
    icone: Calendar,
    cor: "text-sky-400",
    bg: "bg-sky-500/10",
    borderCor: "border-sky-500/40",
    desc: "Dispara periodicamente via expressão cron ou intervalo",
  },
  {
    tipo: "webhook",
    rotulo: "Gatilho Webhook",
    categoria: "gatilhos",
    icone: Webhook,
    cor: "text-amber-400",
    bg: "bg-amber-500/10",
    borderCor: "border-amber-500/40",
    desc: "Dispara ao receber requisições HTTP externas no endpoint",
  },
  {
    tipo: "manual",
    rotulo: "Gatilho Manual / Test",
    categoria: "gatilhos",
    icone: Play,
    cor: "text-zinc-300",
    bg: "bg-zinc-500/10",
    borderCor: "border-zinc-500/40",
    desc: "Disparo sob demanda direto pelo studio ou botão de teste",
  },

  // Agentes & Inteligência
  {
    tipo: "agente",
    rotulo: "Agente Executor",
    categoria: "agentes",
    icone: Bot,
    cor: "text-emerald-400",
    bg: "bg-emerald-500/10",
    borderCor: "border-emerald-500/40",
    desc: "Executa instruções e tarefas com LLMs especializadas",
  },
  {
    tipo: "fanout",
    rotulo: "Equipe Fan-Out",
    categoria: "agentes",
    icone: Users,
    cor: "text-teal-400",
    bg: "bg-teal-500/10",
    borderCor: "border-teal-500/40",
    desc: "Executa múltiplos agentes em paralelo para tarefas concorrentes",
  },
  {
    tipo: "review",
    rotulo: "Equipe Review",
    categoria: "agentes",
    icone: ShieldCheck,
    cor: "text-violet-400",
    bg: "bg-violet-500/10",
    borderCor: "border-violet-500/40",
    desc: "Pipeline de autor-revisor com critérios de aprovação",
  },
  {
    tipo: "debate",
    rotulo: "Equipe Debate",
    categoria: "agentes",
    icone: Users,
    cor: "text-pink-400",
    bg: "bg-pink-500/10",
    borderCor: "border-pink-500/40",
    desc: "Deliberação e dialética entre agentes com síntese final",
  },

  // Lógica & Controle (Estilo n8n)
  {
    tipo: "condicao",
    rotulo: "Condição / Se-Então",
    categoria: "logica",
    icone: GitBranch,
    cor: "text-amber-400",
    bg: "bg-amber-500/10",
    borderCor: "border-amber-500/40",
    desc: "Avalia expressão booleana e bifurca em caminhos então / senão",
  },
  {
    tipo: "decisao",
    rotulo: "Decisão / Roteamento",
    categoria: "logica",
    icone: HelpCircle,
    cor: "text-amber-400",
    bg: "bg-amber-500/10",
    borderCor: "border-amber-500/40",
    desc: "Bifurcação e roteamento condicional com base em critérios",
  },
  {
    tipo: "subflow",
    rotulo: "Executar Sub-Fluxo",
    categoria: "logica",
    icone: Workflow,
    cor: "text-purple-400",
    bg: "bg-purple-500/10",
    borderCor: "border-purple-500/40",
    desc: "Invoca e executa outro fluxo modular deste workspace",
  },
  {
    tipo: "loop",
    rotulo: "Loop / Repetição",
    categoria: "logica",
    icone: RefreshCw,
    cor: "text-orange-400",
    bg: "bg-orange-500/10",
    borderCor: "border-orange-500/40",
    desc: "Controle de repetição, feedback e parada para HLE",
  },
  {
    tipo: "delay",
    rotulo: "Aguardar / Delay",
    categoria: "logica",
    icone: Clock,
    cor: "text-yellow-400",
    bg: "bg-yellow-500/10",
    borderCor: "border-yellow-500/40",
    desc: "Pausa a execução por um intervalo de segundos (ex: 30s)",
  },

  // Integrações & Execução
  {
    tipo: "script",
    rotulo: "Script do Workspace",
    categoria: "integracoes",
    icone: Terminal,
    cor: "text-cyan-400",
    bg: "bg-cyan-500/10",
    borderCor: "border-cyan-500/40",
    desc: "Executa scripts locais (.js, .py, .sh) ou comandos bash",
  },
  {
    tipo: "http_request",
    rotulo: "Requisição HTTP / API",
    categoria: "integracoes",
    icone: Globe,
    cor: "text-blue-400",
    bg: "bg-blue-500/10",
    borderCor: "border-blue-500/40",
    desc: "Chama APIs REST externas (GET, POST, Webhooks de saída)",
  },
  {
    tipo: "componente",
    rotulo: "Componente Modular",
    categoria: "integracoes",
    icone: Code2,
    cor: "text-teal-400",
    bg: "bg-teal-500/10",
    borderCor: "border-teal-500/40",
    desc: "Componente customizado reutilizável com entrada e saída",
  },

  // Governança & Persistência
  {
    tipo: "saida",
    rotulo: "Saída do Fluxo",
    categoria: "governanca",
    icone: CheckCircle,
    cor: "text-emerald-400",
    bg: "bg-emerald-500/10",
    borderCor: "border-emerald-500/40",
    desc: "Finaliza o pipeline e retorna os dados de contexto resultantes",
  },
  {
    tipo: "task_create",
    rotulo: "Criar Tarefa Kanban",
    categoria: "governanca",
    icone: Layers,
    cor: "text-blue-400",
    bg: "bg-blue-500/10",
    borderCor: "border-blue-500/40",
    desc: "Cria um card no Kanban com título, coluna e prioridade",
  },
  {
    tipo: "reuniao",
    rotulo: "Reunião de Agentes",
    categoria: "governanca",
    icone: Users,
    cor: "text-indigo-400",
    bg: "bg-indigo-500/10",
    borderCor: "border-indigo-500/40",
    desc: "Convoca mesa de deliberação coletiva entre múltiplos agentes",
  },
  {
    tipo: "registro",
    rotulo: "Registro / Documento",
    categoria: "governanca",
    icone: FileText,
    cor: "text-purple-400",
    bg: "bg-purple-500/10",
    borderCor: "border-purple-500/40",
    desc: "Grava ata, parecer ou relatório nos registries da empresa",
  },
];

export function obterItemCatalogo(tipo: string): TipoNodeItem {
  const achado = TIPOS_NODE_CATALOGO.find((t) => t.tipo === tipo);
  if (achado) return achado;
  return {
    tipo,
    rotulo: tipo.charAt(0).toUpperCase() + tipo.slice(1),
    categoria: "integracoes",
    icone: Terminal,
    cor: "text-zinc-400",
    bg: "bg-zinc-800/40",
    borderCor: "border-zinc-700",
    desc: "Nó customizado do fluxo",
  };
}
